// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.0'
        classpath 'com.google.gms:google-services:4.4.4'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

apply from: "variables.gradle"

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

subprojects { subproject ->
    if (subproject.name.startsWith('capacitor')) {
        subproject.tasks.withType(JavaCompile).configureEach {
            options.warnings = false
            options.compilerArgs += ['-Xlint:none']
        }

        subproject.tasks.configureEach { task ->
            if (task.class.name == 'org.jetbrains.kotlin.gradle.tasks.KotlinCompile') {
                task.kotlinOptions {
                    suppressWarnings = true
                }
            }
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
